Repository javpacmar/Acme-Toolkits, pull requests merged in 2022-05, with the labels that each got.

#199 Task 069/task 070
  src/main/java/acme/features/any/items/package-info.java
  src/main/java/acme/features/inventor/items/InventorComponentListService.java
  src/main/java/acme/features/inventor/items/InventorItemsController.java
  src/main/java/acme/features/inventor/items/InventorItemsCreateService.java
  src/main/java/acme/features/inventor/items/InventorItemsDeleteService.java
  src/main/java/acme/features/inventor/items/InventorItemsPublishedService.java
  src/main/java/acme/features/inventor/items/InventorItemsRepository.java
  src/main/java/acme/features/inventor/items/InventorItemsShowService.java
  src/main/java/acme/features/inventor/items/InventorItemsUpdateService.java
  src/main/java/acme/features/inventor/items/InventorToolListService.java
  src/main/java/acme/features/inventor/items/package-info.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/list.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
Labels: enhancement 🦄

#200 Task 067
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorController.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorCreateService.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorRepository.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorUpdateService.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronController.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronCreateService.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronRepository.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronUpdateService.java
  src/main/webapp/WEB-INF/views/authenticated/inventor/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/patron/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement 🦄

#205 Task 084/test tool component
  src/main/java/acme/features/inventor/items/InventorItemsShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
  src/test/java/acme/testing/inventor/item/InventorItemCreateTest.java
  src/test/java/acme/testing/inventor/item/InventorItemDeleteTest.java
  src/test/java/acme/testing/inventor/item/InventorItemUpdateTest.java
  src/test/java/acme/testing/inventor/item/InventorPublishedTest.java
  src/test/resources/inventor/item/createComponent.csv
  src/test/resources/inventor/item/createTool.csv
  src/test/resources/inventor/item/deleteComponent.csv
  src/test/resources/inventor/item/deleteTool.csv
  src/test/resources/inventor/item/negativeCreateComponent.csv
  src/test/resources/inventor/item/negativeCreateTool.csv
  src/test/resources/inventor/item/negativeDeleteComponent.csv
  src/test/resources/inventor/item/negativeDeleteTool.csv
  src/test/resources/inventor/item/negativePublishedComponent.csv
  src/test/resources/inventor/item/negativePublishedTool.csv
  src/test/resources/inventor/item/negativeUpdateComponent.csv
  src/test/resources/inventor/item/negativeUpdateTool.csv
  src/test/resources/inventor/item/publishedComponent.csv
  src/test/resources/inventor/item/publishedTool.csv
  src/test/resources/inventor/item/updateComponent.csv
  src/test/resources/inventor/item/updateTool.csv
Labels: testing ✅

#211 Fix inventorItemTest: done
  src/test/java/acme/testing/inventor/item/InventorItemTest.java
  src/test/resources/inventor/item/itemComponent.csv
  src/test/resources/inventor/item/itemTool.csv
Labels: bug 🐛, testing ✅

#213 Task-084/05: Done
  reports/model.uxf
  src/main/java/acme/entities/configuration/SystemConfiguration.java
  src/test/java/acme/testing/administrator/systemConfiguration/AdministratorSystemConfigurationUpdateTest.java
  src/test/resources/administrator/systemConfiguration/update-negative.csv
  src/test/resources/administrator/systemConfiguration/update-positive.csv
Labels: bug 🐛, testing ✅

#218 Task 67: Fix
  bin/src/main/java/acme/features/any/chirp/AnyChirpController.class
  bin/src/main/webapp/WEB-INF/views/any/chirp/list.jsp
  bin/src/main/webapp/WEB-INF/views/any/chirp/messsages-en.i18n
  bin/src/main/webapp/WEB-INF/views/any/chirp/messsages-es.i18n
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorCreateService.java
  src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorUpdateService.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronCreateService.java
  src/main/java/acme/features/authenticated/patron/AuthenticatedPatronUpdateService.java
  src/main/webapp/WEB-INF/views/authenticated/inventor/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/patron/messsages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/patron/messsages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
Labels: bug 🐛

#216 Feature #215: done
  src/main/java/acme/features/inventor/items/InventorItemsCreateService.java
  src/main/java/acme/features/inventor/items/InventorItemsDeleteService.java
  src/main/java/acme/features/inventor/items/InventorItemsPublishedService.java
  src/main/java/acme/features/inventor/items/InventorItemsUpdateService.java
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
  src/test/java/acme/testing/inventor/item/InventorItemCreateTest.java
  src/test/java/acme/testing/inventor/item/InventorItemUpdateTest.java
Labels: bug 🐛

#220 Fix: Eliminado provider y consumer de la al iniciar sesión como admin
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: bug 🐛

#228 Task 073: done.
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportController.java
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportCreateService.java
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/list.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messsages-es.i18n
Labels: enhancement 🦄

#229 Task 084/02
  src/test/java/acme/testing/authenticathed/userAccount/AuthenticatedUserAccountUpdateTest.java
  src/test/resources/authenticated/userAccount/updateUserAccount.csv
  src/test/resources/authenticated/userAccount/updateUserAccountNegative.csv
Labels: testing ✅

#232 Task 084/04: done
  src/test/java/acme/testing/any/chirps/AnyCreateChirpsTest.java
  src/test/resources/any/chirp/chirpCreate.csv
Labels: testing ✅

#236 Task 069 070/ update fix
  src/main/java/acme/features/inventor/items/InventorItemsPublishedService.java
  src/main/java/acme/features/inventor/items/InventorItemsRepository.java
  src/main/java/acme/features/inventor/items/InventorItemsUpdateService.java
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
  src/test/java/acme/testing/inventor/item/InventorItemUpdateTest.java
  src/test/resources/inventor/item/negativeUpdateComponent.csv
  src/test/resources/inventor/item/negativeUpdateTool.csv
  src/test/resources/inventor/item/updateComponent.csv
  src/test/resources/inventor/item/updateTool.csv
Labels: bug 🐛

#239 Task 84/03: improve
  src/test/java/acme/testing/any/chirps/AnyCreateChirpsTest.java
  src/test/resources/any/chirp/chirpCreate.csv
Labels: testing ✅

#240 Task 84/03: Negative tests
  src/test/java/acme/testing/any/chirps/AnyCreateChirpsTest.java
  src/test/resources/any/chirp/chirpNoCreate.csv
Labels: testing ✅

#249 Task 078
  src/main/java/acme/features/any/items/AnyItemsShowService.java
  src/main/java/acme/features/inventor/items/InventorItemsShowService.java
  src/main/java/acme/features/inventor/patronageReport/InventorPatronageReportShowService.java
  src/main/java/acme/features/inventor/patronages/InventorPatronageShowService.java
  src/main/java/acme/features/patron/patronages/PatronPatronageShowService.java
  src/main/webapp/WEB-INF/views/any/item/form.jsp
  src/main/webapp/WEB-INF/views/any/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/any/item/messsages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messsages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage/messsages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/messsages-es.i18n
  src/main/webapp/WEB-INF/views/patron/patronage/form.jsp
  src/main/webapp/WEB-INF/views/patron/patronage/messsages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patronage/messsages-es.i18n
Labels: enhancement 🦄

#254 Task 084/FAA: done.
  src/main/webapp/WEB-INF/resources/sample-data/announcement.csv
  src/test/resources/authenticated/announcement/announcement-list.csv
Labels: bug 🐛

#255 Task-084/08: Done -feature #245
  src/test/java/acme/testing/inventor/patronages/InventorPatronageAcceptTest.java
  src/test/java/acme/testing/inventor/patronages/InventorPatronageDenieTest.java
  src/test/resources/inventor/patronage/acceptPatronage.csv
  src/test/resources/inventor/patronage/deniePatronage.csv
  src/test/resources/inventor/patronage/negativeAcceptPatronage.csv
  src/test/resources/inventor/patronage/negativeDeniePatronage.csv
Labels: testing ✅

#260 Hotfix
  src/test/resources/any/chirp/chirpCreate.csv
Labels: testing ✅
